version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.3.0
jobs:
  cljs:
    docker:
      - image: cimg/clojure:1.10.3-browsers
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - restore_cache:
          key: cljs-{{ checksum "deps.edn" }}-{{ checksum "package.json" }}
      - run: npm install
      - run: npx shadow-cljs compile test-ci
      - save_cache:
          paths:
          - node_modules
          - ~/.m2
          key: cljs-{{ checksum "deps.edn" }}-{{ checksum "package.json" }}
      - run: npx karma start --single-run
workflows:
  version: 2
  fullstack:
    jobs:
      - cljs

